# tools/chart/templates/secret.yaml

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/component: {{ .Values.service.name }}
type: Opaque
stringData:
  GEOCODING_API_KEY: {{ .Values.geocoding.apiKey | quote }}
