# database/chart/templates/secret.yaml

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.app }}
    app.kubernetes.io/component: {{ .Values.service.name }}
type: Opaque
stringData:
  PGDATABASE: {{ .Values.database.name | quote }}
  PGUSER: {{ .Values.database.user | quote }}
  PGPASSWORD: {{ .Values.database.password | quote }}
