services:
  database:
    profiles: [all, inference, backend, database]
    build: database
    image: squidfall/database:latest
    container_name: squidfall-database
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d squidfall"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  backend:
    profiles: [all, inference, backend]
    build: backend
    image: squidfall/backend:latest
    container_name: squidfall-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/api/v1/health/ > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  tools:
    profiles: [all, inference, tools]
    build: tools
    image: squidfall/tools:latest
    container_name: squidfall-tools
    ports:
      - "8002:8002"
    env_file:
      - tools/.env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8002/api/v1/health/ > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  inference:
    profiles: [all, inference]
    build: inference
    image: squidfall/inference:latest
    container_name: squidfall-inference
    ports:
      - "8001:8001"
    env_file:
      - inference/.env
    depends_on:
      backend:
        condition: service_healthy
      tools:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8001/api/v1/health/ > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  frontend:
    profiles: [all, frontend]
    build:
      context: frontend
      args:
        LANGGRAPH_DEPLOYMENT_URL: "http://squidfall-inference:8001"
    image: squidfall/frontend:latest
    container_name: squidfall-frontend
    ports:
      - "8080:8080"
    env_file:
      - frontend/.env

volumes:
  database:
