services:

  backend:
    profiles: [ all, backend ]
    build: backend
    image: squidfall/backend:latest
    container_name: squidfall-backend
    env_file:
      - backend/.env

  database:
    profiles: [ all, database ]
    build: database
    image: squidfall/database:latest
    container_name: squidfall-database
    env_file:
      - database/.env

  frontend:
    profiles: [ all, frontend ]
    build: frontend
    image: squidfall/frontend:latest
    container_name: squidfall-frontend
    env_file:
      - frontend/.env

  inference:
    profiles: [ all, inference ]
    build: inference
    image: squidfall/inference:latest
    container_name: squidfall-inference
    env_file:
      - inference/.env

  tools:
     profiles: [ all, tools ]
     build: tools
     image: squidfall/tools:latest
     container_name: squidfall-tools
     env_file:
       - tools/.env
