# uds-package.yaml

---
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  namespace: squidfall
  name: squidfall
spec:
  network:
    allow:
      - description: Inbound to database
        remoteGenerated: IntraNamespace
        direction: Ingress
        selector:
          app.kubernetes.io/component: database
        port: 5432
      - description: Inbound to backend
        remoteGenerated: IntraNamespace
        direction: Ingress
        selector:
          app.kubernetes.io/component: backend
        port: 8000
      - description: Inbound to tools
        remoteGenerated: IntraNamespace
        direction: Ingress
        selector:
          app.kubernetes.io/component: tools
        port: 8002
      - description: Inbound to inference
        remoteGenerated: IntraNamespace
        direction: Ingress
        selector:
          app.kubernetes.io/component: inference
        port: 8001
      - description: Outbound to internal services
        remoteGenerated: IntraNamespace
        direction: Egress
        ports:
          - 5432
          - 8000
          - 8001
          - 8002
      - description: Outbound to model provider
        direction: Egress
        selector:
          app.kubernetes.io/component: inference
        remoteHost: api.openai.com
        port: 443
    expose:
      - service: frontend
        selector:
          app.kubernetes.io/component: frontend
        host: squidfall
        port: 8080
  sso:
    - name: squidfall
      clientId: squidfall
      redirectUris:
        - https://squidfall.uds.dev/login
      enableAuthserviceSelector:
        app.kubernetes.io/component: frontend
