# uds-package.yaml

---
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  namespace: squidfall
  name: squidfall
spec:
  network:
    allow:
      # Allow all the pods in the app to talk to each other.
      - description: Inbound internally
        remoteGenerated: IntraNamespace
        direction: Ingress
        selector:
          app.kubernetes.io/app: squidfall
      - description: Outbound internally
        remoteGenerated: IntraNamespace
        direction: Egress
        selector:
          app.kubernetes.io/app: squidfall
      
      # Allow traffic to specific external endpoints.
      - description: Outbound to model provider
        direction: Egress
        selector:
          app.kubernetes.io/component: inference
        port: 443
        remoteHost: api.openai.com
      - description: Outbound to the Geocoding API
        direction: Egress
        selector:
          app.kubernetes.io/component: tools
        port: 443
        remoteHost: geocode.maps.co
      - description: Outbound to the Weather API
        direction: Egress
        selector:
          app.kubernetes.io/component: tools
        port: 443
        remoteHost: api.weather.gov
    
    # Allow user traffic to the frontend.
    expose:
      - service: frontend
        selector:
          app.kubernetes.io/component: frontend
        host: squidfall
        port: 8080

  # Put the frontend behind a MFA-wall.
  sso:
    - name: squidfall
      clientId: squidfall
      redirectUris:
        - https://squidfall.uds.dev/login
      enableAuthserviceSelector:
        app.kubernetes.io/component: frontend
