# tools/chart/values.yaml

---
app: squidfall
namespace: squidfall
replicaCount: 1
image: 
  pullPolicy: Always
  repository: squidfall/tools
  tag: latest
service: 
  type: ClusterIP
  name: tools
  port: 8002
geocoding:
  apiKey: "###ZARF_VAR_GEOCODING_APIKEY###"
