# frontend/chart/values.yaml

---
namespace: squidfall
replicaCount: 1
image: 
  pullPolicy: Always
  repository: squidfall/frontend
  tag: latest
service: 
  type: ClusterIP
  name: frontend
  port: 8080
  hostname: 0.0.0.0
langgraph:
  deployment:
    url: http://squidfall-inference:8001/api/v1
copilotkit:
  telemetry:
    disabled: true
