# inference/chart/templates/secret.yaml

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/component: {{ .Values.service.name }}
type: Opaque
stringData:
  TOOLS_ENDPOINT: {{ .Values.tools.endpoint | quote }}
  BACKEND_ENDPOINT:  {{ .Values.backend.endpoint | quote }}
  MODEL_PROVIDER: {{ .Values.model.provider | quote }}
  OPENAI_MODEL: {{ .Values.openai.model | quote }}
  OPENAI_API_KEY: {{ .Values.openai.apiKey | quote }}
