# frontend/chart/templates/secret.yaml

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/component: {{ .Values.service.name }}
type: Opaque
stringData:
  LANGGRAPH_DEPLOYMENT_URL: {{ .Values.langgraph.deployment.url | quote }}
  COPILOTKIT_TELEMETRY_DISABLED: {{ .Values.copilotkit.telemetry.disabled | quote }}
  PORT: {{ .Values.service.port | quote }}
  HOSTNAME: {{ .Values.service.hostname | quote }}
