# Generated by Django 6.1.1 on 2026-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(max_length=255)),
                ("checkpoint_ns", models.CharField(default="", max_length=255)),
                ("checkpoint_id", models.CharField(max_length=255, unique=True)),
                (
                    "parent_checkpoint_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(max_length=50)),
                ("checkpoint", models.TextField()),
                ("metadata_type", models.CharField(max_length=50)),
                ("metadata", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
