# backend/chart/templates/secret.yaml

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/component: {{ .Values.service.name }}
type: Opaque
stringData:
  DB_ENGINE: {{ .Values.database.engine | quote }}
  PGHOST: {{ .Values.database.host | quote }}
  PGDATABASE: {{ .Values.database.name | quote }}
  PGPORT: {{ .Values.database.port | quote }}
  PGSSLMODE: {{ .Values.database.sslmode | quote }}
  PGUSER: {{ .Values.database.user | quote }}
  PGPASSWORD: {{ .Values.database.password | quote }}
  SECRET_KEY: {{ .Values.database.secret_key | quote }}
